env:
    # OrangeFox Sync Repository
    TW_SYNC: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git

    # Device
    TW_BRANCH: twrp-12.1
    DT_LINK: https://github.com/realme-mt6877/android_device_realme_rmx3392_twrp.git
    DEVICE: RMX3392
    OEM: realme
    TARGET: recoveryimage

    DT_PATH: device/$OEM/$DEVICE
    OUTPUT: TWRP*.zip

    # Not Recommended to Change
    SYNC_BRANCH: ${TW_BRANCH}
    SYNC_PATH: $HOME/work # Full (absolute) path. Use "$HOME" instead of "~".
    USE_CCACHE: 1
    CCACHE_SIZE: 50G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: ENCRYPTED[e71e4118b2ec3509700ba9a0b99627f22c7741572d02ee52e507341c4c3c24601bbec75329f67f260b3d98d066a545f9]
    TG_TOKEN: ENCRYPTED[29fedafd88f2250ee816d30f9390c8c4d703c95413f05744f5989da3acf2170b07d8aba426c7b23c04d52ef9f100f1ee]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/alone03161/docker:arch
      cpu: 8
      memory: 20G

  Checks_script:
      - curl -sL https://raw.githubusercontent.com/Alone0316/twrp-builder/main/scripts/checks.sh | bash

  Sync_script:
      - curl -sL https://raw.githubusercontent.com/Alone0316/twrp-builder/main/scripts/sync.sh | bash
      - (bash -c "$command" | tee sync.txt) || true
      - a=$(grep 'Cannot remove project' sync.txt || true)
      - b=$(grep "^fatal: remove-project element specifies non-existent project" sync.txt || true)
      - if [[ $a == *'Cannot remove project'* ]]
      - then
      - a=$(echo $a | cut -d ':' -f2)
      - rm -rf $a
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)
      - elif [[ $b == *'remove-project element specifies non-existent'* ]]
      - then exit 1
      - else
      - (repo forall -c 'git checkout .' && bash -c "$only_sync") || (find -name shallow.lock -delete && find -name index.lock -delete && bash -c "$only_sync")
      - fi
      - rm -rf sync.txt

  Build_script:
      - curl -sL https://raw.githubusercontent.com/Alone0316/twrp-builder/main/scripts/build.sh | bash

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - curl https://raw.githubusercontent.com/Alone0316/twrp-builder/main/scripts/upload.sh | bash
